volumes:
  mongo-data:
    external: true
services:
  mongo:
    image: mongo:5
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: nomad-nerds
      MONGO_INITDB_ROOT_PASSWORD: nomad-nerds
  api-yelp:
    build:
      context: ./api-yelp
      dockerfile: ./Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./api-yelp:/app
    environment:
      DATABASE_URL: mongodb://root:password@mongo
      DATABASE_NAME: db-name
      WAIT_HOSTS: mongo:27017
  business:
    build:
      context: ./business
      dockerfile: ./Dockerfile.dev
    ports:
      - "8001:8000"
    volumes:
      - ./business:/app
    environment:
      DATABASE_URL: postgresql://user-name:password@postgres/db-name
      WAIT_HOSTS: postgres:5432
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      REACT_APP_API-YELP: http://localhost:8000
      REACT_APP_BUSINESS: http://localhost:8001
      REACT_APP_THIRD_PARTY_SERVICE: https://api.yelp.com/v3