cities = [
    "London",
    "Paris",
    "New York",
    "Amsterdam",
    "Rome",
    "Venice",
    "Barcelona",
    "Prague",
    "Vienna",
    "Los Angeles",
    "Florence",
    "San Francisco",
    "Berlin",
    "Brussels",
    "Las Vegas",
    "Washington",
    "Edinburgh",
    "Munich",
    "Budapest",
    "Dublin",
    "Copenhagen",
    "Madrid",
    "Bangkok",
    "Athens",
    "Bath",
    "Lisbon",
    "Singapore",
    "Istanbul",
    "Toronto",
    "Chicago",
    "Hong Kong",
    "Sydney",
    "Stockholm",
    "Miami",
    "Monaco",
    "Naples",
    "York",
    "Vancouver",
    "Glasgow, Scotland",
    "Seattle",
    "Krakow",
    "Manchester",
    "Montreal",
    "Dubai",
    "Dubrovnik, Croatia",
    "Tokyo",
    "New Orleans",
    "Luxembourg",
    "Helsinki",
    "Seville",
    "Kuala Lumpur",
    "Hamburg",
    "Beijing",
    "Innsbruck",
    "Tallinn",
    "Bratislava",
    "Siena, Italy",
    "St. Petersburg",
    "Reykjavik",
    "Melbourne",
    "Cairo",
    "Marrakesh",
    "Kyoto",
    "Shanghai",
    "Valletta",
    "Ljubljana",
    "Heidelberg, Germany",
    "Auckland",
    "Jerusalem",
    "Cardiff, Wales",
    "Quebec City",
    "Hanoi",
    "Bern",
    "Moscow",
    "Ho Chi Minh City",
    "Galway",
    "Delhi",
    "Marseille",
    "Belfast",
    "Riga",
    "Cape Town",
    "Memphis",
    "Zagreb",
    "Macau",
    "Bled",
    "Rio De Janeiro",
    "Buenos Aires",
    "Tel Aviv",
    "Seoul",
    "Cuzco",
    "Phnom Penh",
    "Jalour",
    "Mexico City",
    "Christchurch",
    "Sofia",
    "Wellington",
    "Chiang Mai",
    "Vilnius",
    "Bucharest",
    "Hoi An",
    "Havana",
    "Perth",
    "Belgrade",
    "San Juan",
    "Savannah",
    "Taipei",
    "Hiroshima",
    "Fes",
    "Johannesburg",
    "Lubeck",
    "Carcassone",
    "Mumbai",
    "Georgetown",
    "Austin",
    "Aswan, Egypt",
    "Bridgetown",
    "Hobart",
    "Amman",
    "Manila",
    "Saraievo",
    "Nairobi",
    "Santiago",
    "Antigua",
    "Kiev",
    "Puerto Vallarta",
    "Zanzibar",
    "San Sebastian",
    "Luang Prabang",
    "Anchorage",
    "Kathmandu",
    "Panama City",
    "Belize City",
    "Quito",
    "Varanasi",
    "Cartagena",
    "Yogyakarta",
    "Muscat",
    "Arequipa",
    "Essaouira",
    "Alexandria",
    "Suva",
    "Valparaiso",
    "Yangon",
    "Montevidec",
    "Tirana",
    "Male, Maldives",
    "Tbilisi",
    "Bogota",
    "Dar Es Salaam",
    "Oaxaca",
    "Santo Domingo",
    "Laval",
    "Beirut",
    "La Paz",
    "Mombasa",
    "Livingstone",
    "Salvador Da Bahia",
    "Kolkata",
    "Kampala",
    "Caracas",
    "Ushuaia",
    "Minsk",
    "Ulaanbaatar",
    "Damascus",
    "Kairouan",
    "Addis Ababa",
    "Bukhara",
    "Baku",
    "Yerevan",
    "Ifahan",
    "Lhasa",
    "Mendoza",
    "Dakar",
    "Aleppo",
    "Granada",
    "Apia",
    "Sanaa",
    "Kabul",
    "Dhaka",
    "Saint-Denis",
    "Maputo",
    "Abuja",
    "San Salvador",
    "Almaty",
    "Antananarivo",
    "Bamako",
    "Thimphu",
    "Jeddah",
    "Pyongyang",
    "Lahore",
    "Asmara",
    "Nuuk",
    "Khartoum",
    "San Cristobal",
    "Agadez",
    "Mecca",
    "Cayenne",
    "Ashgabat",
    "Madang",
    "Beira",
]


us_cities = [
    "AKRON",
    "ALBANY",
    "ALBUQUERQUE",
    "ALLENTOWN",
    "ATLANTA",
    "AUGUSTA",
    "AUSTIN",
    "BAKERSFIELD",
    "BALTIMORE",
    "BIRMINGHAM",
    "BOISE CITY",
    "BOSTON",
    "BRIDGEPORT",
    "BUFFALO",
    "CAPE CORAL",
    "CHARLESTON",
    "CHARLOTTE",
    "CHATTANOOGA",
    "CHICAGO",
    "CINCINNATI",
    "CLEVELAND",
    "COLORADO SPRINGS",
    "COLUMBIA",
    "COLUMBUS",
    "DALLAS",
    "DENVER",
    "DES MOINES",
    "DETROIT",
    "DURHAM",
    "EL PASO",
    "FAYETTEVILLE",
    "FRESNO",
    "GRAND RAPIDS",
    "GREENSBORO",
    "GREENVILLE",
    "HARRISBURG",
    "HARTFORD",
    "HOUSTON",
    "INDIANAPOLIS",
    "JACKSONVILLE",
    "KANSAS CITY",
    "KNOXVILLE",
    "LAKELAND",
    "LANCASTER",
    "LANSING",
    "LAS VEGAS",
    "LEXINGTON",
    "LITTLE ROCK",
    "LOS ANGELES",
    "LOUISVILLE",
    "MADISON",
    "MCALLEN",
    "MEMPHIS",
    "MIAMI",
    "MILWAUKEE",
    "MINNEAPOLIS",
    "MODESTO",
    "NASHVILLE",
    "NEW HAVEN",
    "NEW ORLEANS",
    "NEW YORK",
    "NORTH PORT",
    "OGDEN",
    "OKLAHOMA CITY",
    "OMAHA",
    "ORLANDO",
    "OXNARD",
    "PALM BAY",
    "PENSACOLA",
    "PHILADELPHIA",
    "PHOENIX",
    "PITTSBURGH",
    "PORTLAND",
    "POUGHKEEPSIE NY",
    "PROVIDENCE",
    "PROVO",
    "RALEIGH",
    "RICHMOND",
    "RIVERSIDE",
    "ROCHESTER",
    "SACRAMENTO",
    "SALT LAKE CITY",
    "SAN ANTONIO",
    "SAN DIEGO",
    "SAN FRANCISCO",
    "SAN JOSE",
    "SEATTLE",
    "SPOKANE",
    "SPRINGFIELD",
    "ST LOUIS",
    "STOCKTON",
    "TAMPA",
    "TUCSON",
    "TULSA",
    "URBAN HONOLULU",
    "VIRGINIA BEACH",
    "WASHINGTON",
    "WICHITA",
    "WORCESTER",
]
